Suggest 'asdf' recovery when Ruby is borked
Ruby can be borked on Gitpod restart, because HOME is reset to its
pristine state in docker image.

diff --git a/bin/gdk b/bin/gdk
--- a/bin/gdk
+++ b/bin/gdk
@@ -25,7 +25,15 @@ gdk_root_path=$(find_gdk_root "$(pwd)")
 debug "gdk_root_path: $gdk_root_path"
 
 if [[ -d "${gdk_root_path}" ]]; then
-  exec "${gdk_root_path}/gem/bin/gdk" "${@}"
+  "${gdk_root_path}/gem/bin/gdk" "${@}"
+  exit_status=$?
+  debug "ruby GDK exit status $exit_status"
+  if (( $exit_status == 126 )); then
+    echo -e "\nERROR: failed to start 'gem/bin/gdk' ruby script, try 'asdf' recovery procedure"
+    echo "  asdf update"
+    echo "  asdf plugin-update ruby"
+    echo "  asdf install ruby"
+  fi
 else
   echo "ERROR: The current working directory is not a GDK." >&2
 fi
