Change to GDK dir to install proper Ruby versions

diff --git a/bin/gdk b/bin/gdk
--- a/bin/gdk
+++ b/bin/gdk
@@ -32,8 +32,8 @@ if [[ -d "${gdk_root_path}" ]]; then
   debug "ruby GDK exit status ${gdk_exit_status}"
 
   if [[ $gdk_exit_status == "$ERROR_CODE_ASDF_SHIM_BINARY_NOT_FOUND" ]]; then
-    echo -e "\nERROR: failed to start 'gem/bin/gdk' ruby script, try 'asdf' recovery procedure by running:" >&2
-    echo "  asdf update && asdf plugin-update ruby && asdf install ruby"
+    echo -e "\nERROR: failed to run 'gem/bin/gdk' Ruby script, try 'asdf' recovery procedure by running:" >&2
+    echo "  cd ${gdk_root_path} && asdf update && asdf plugin-update ruby && asdf install ruby"
   fi
 else
   echo "ERROR: The current working directory is not a GDK." >&2
