Check gdk.use_bash_shim before installing gem

diff --git a/support/asdf-update b/support/asdf-update
--- a/support/asdf-update
+++ b/support/asdf-update
@@ -84,8 +84,8 @@ if ! asdf_reshim; then
   error "Failed to reshim asdf." >&2
 fi
 
-if ! gdk_install_gem; then
-  error "Failed to install gitlab-development-kit Ruby gem." >&2
+if ! gdk_install_gdk_clt; then
+  error "Failed to run gdk_install_gdk_clt()." >&2
 fi
 
 if ! configure_ruby_bundler; then
diff --git a/support/bootstrap b/support/bootstrap
--- a/support/bootstrap
+++ b/support/bootstrap
@@ -113,9 +113,8 @@ if ! asdf_reshim; then
   error "Failed to reshim asdf." >&2
 fi
 
-echo "INFO: Installing gitlab-development-kit Ruby gem.."
-if ! gdk_install_gem; then
-  error "Failed to install gitlab-development-kit Ruby gem." >&2
+if ! gdk_install_gdk_clt; then
+  error "Failed to run gdk_install_gdk_clt()." >&2
 fi
 
 echo "INFO: Preparing GDK directory.."
