Rename to configure_ruby_bundler_for_gitlab

diff --git a/support/asdf-update b/support/asdf-update
--- a/support/asdf-update
+++ b/support/asdf-update
@@ -74,6 +74,6 @@ if ! gdk_install_gdk_clt; then
   error "Failed to run gdk_install_gdk_clt()." >&2
 fi
 
-if ! configure_ruby_bundler; then
-  error "Failed to configure Ruby Bundler." >&2
+if ! configure_ruby; then
+  error "Failed to configure Ruby." >&2
 fi
