Minor wording fix if asdf install fails

diff --git a/support/bootstrap b/support/bootstrap
--- a/support/bootstrap
+++ b/support/bootstrap
@@ -270,7 +270,7 @@ fi
 
 echo "INFO: Installing asdf.."
 if ! asdf_install; then
-  error "asdf install failed to install." >&2
+  error "Failed to install asdf." >&2
 fi
 
 echo "INFO: Installing asdf plugins.."
