bootstrap: Add config to opt out of preflight step

diff --git a/support/bootstrap b/support/bootstrap
--- a/support/bootstrap
+++ b/support/bootstrap
@@ -87,7 +87,9 @@ if [[ -f "${GDK_BOOTSTRAPPED_FILE}" ]]; then
   exit 0
 fi
 
-common_preflight_checks
+if ! common_preflight_checks; then
+  error "Failed to perform preflight checks." >&2
+fi
 
 if ! setup_platform; then
   error "Failed to install set up platform." >&2
diff --git a/support/platform-update b/support/platform-update
--- a/support/platform-update
+++ b/support/platform-update
@@ -35,7 +35,9 @@ asdf_update() {
 
 ###############################################################################
 
-common_preflight_checks
+if ! common_preflight_checks; then
+  error "Failed to perform preflight checks." >&2
+fi
 
 header_print "Ensuring platform software installed"
 if ! setup_platform; then
