xargs on Linux needs -r to ignore if no output

diff --git a/support/bootstrap/install_prerequisites b/support/bootstrap/install_prerequisites
--- a/support/bootstrap/install_prerequisites
+++ b/support/bootstrap/install_prerequisites
@@ -2,7 +2,16 @@
 
 bootstrap_asdf() {
   # Install asdf plugins, e.g. `asdf plugin add ruby`
-  comm -23 <(cut -d ' ' -f 1 .tool-versions | sort) <(asdf plugin list | sort) | xargs -tn1 asdf plugin add
+  if [[ "$OSTYPE" == "darwin"* ]]; then
+    xargs_extra_args=""
+  elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
+    xargs_extra_args="-r"
+  else
+    echo "ERROR: Unsupported platform."
+    exit 1
+  fi
+
+  comm -23 <(cut -d ' ' -f 1 .tool-versions | sort) <(asdf plugin list | sort) | xargs ${xargs_extra_args} -tn1 asdf plugin add
 
   # Install all packages specified in .tool-versions
   MAKELEVEL=0 asdf install
