Update gitpod startup scripts based on current .gitpod.yml in GitLab

diff --git a/support/gitpod/startup-scripts/gitpod-command b/support/gitpod/startup-scripts/gitpod-command
--- a/support/gitpod/startup-scripts/gitpod-command
+++ b/support/gitpod/startup-scripts/gitpod-command
@@ -11,22 +11,34 @@
 # Set this env var in Gitpod with `gp env KEY=value` or here: https://gitpod.io/settings/
 # see https://www.gitpod.io/docs/environment-variables/.
 
-
 set -eo pipefail
 
 source "$HOME/gitpod-common"
 
+[[ -f /workspace/gitpod_start_time.sh ]] && source /workspace/gitpod_start_time.sh
 SECONDS=0
 cd /workspace/gitlab-development-kit
 
-# update GDK when env var GITLAB_UPDATE_GDK in https://gitpod.io/settings/ is set to true
+# Update GDK when env var GITLAB_UPDATE_GDK in https://gitpod.io/settings/ is set to true
 if [ "$GITLAB_UPDATE_GDK" = true ]; then
     log "Updating GDK"
     gdk update
 fi
 
-# GDK start
-log "GDK start"
+# Ensure gdk.yml has correct instance settings
+set_config
+if is_gitpod_instance; then
+  export DEV_SERVER_PUBLIC_ADDR=$(gp url 3808)
+  export RAILS_HOSTS=$(gp url 3000 | sed -e 's+^http[s]*://++')
+  gdk config set gitlab.rails.hostname RAILS_HOSTS
+fi
+
+# Reconfigure GDK
+log "Reconfiguring GDK"
+gdk reconfigure
+
+# Start GDK
+log "Starting GDK"
 gdk start
 
 # Run DB migrations when env var GITLAB_RUN_DB_MIGRATIONS in https://gitpod.io/settings/ is set to true
@@ -35,23 +47,26 @@ if [ "$GITLAB_RUN_DB_MIGRATIONS" = true ]; then
     make gitlab-db-migrate
 fi
 
-# Fix DB key when env var GITLAB_FIX_DB_KEY in https://gitpod.io/settings/ is set to true
-# see https://gitlab.com/gitlab-org/gitlab-foss/-/issues/56403#note_132515069
-if [ "$GITLAB_FIX_DB_KEY" = true ]; then
-    log "Fixing DB key"
-    cd gitlab
-    printf 'ApplicationSetting.last.update_column(:runners_registration_token_encrypted, nil)\nexit\n' | rails c
-    cd -
+# Install Lefthook
+cd /workspace/gitlab-development-kit/gitlab
+bundle exec lefthook install
+git checkout db/structure.sql
+
+# Waiting for GitLab ..
+cd /workspace/gitlab-development-kit
+
+if is_gitpod_instance; then
+  gp ports await 3000
+  printf "Waiting for GitLab at $(gp url 3000) ..."
+  # Check /-/readiness which returns JSON, but we're only interested in the exit code
+  #
+  # We use http://localhost:3000 instead of the public hostname because
+  # It's no longer possible to access as specific cookies are required
+  until curl --silent --no-buffer --fail http://localhost:3000/-/readiness > /dev/null 2>&1; do printf '.'; sleep 5; done && echo ""
+  # Give Gitpod a few more seconds to set up everything ...
+  sleep 5
+  log "$(printf "GitLab is up (took ~%.1f minutes)\n" "$((10*SECONDS/60))e-1")"
+  gp preview "$(gp url 3000)" || true
+  PREBUILD_LOG=(/workspace/.gitpod/prebuild-log-*)
+  [[ -f /workspace/gitpod_start_time.sh ]] && log "$(printf "Took %.1f minutes from https://gitlab.com/gitlab-org/gitlab/-/blob/master/.gitpod.yml being executed through to completion %s\n" "$((10*(($(date +%s)-${START_TIME_IN_SECONDS}))/60))e-1" "$([[ -f "$PREBUILD_LOG" ]] && echo "With Prebuilds")")"
 fi
-
-# Waiting for GitLab ...
-gp await-port 3000
-printf "Waiting for GitLab at %s ..." "$(gp url 3000)"
-until (curl -sNL "$(gp url 3000)" | grep -q "GitLab"); do printf '.'; sleep 5; done && echo ""
-
-# Give Gitpod a few more seconds to set up everything ...
-sleep 5
-log "$(printf "GitLab is up (took ~%.1f minutes)\n" "$((10*SECONDS/60))e-1")"
-gp preview "$(gp url 3000)" || true
-
-cd "$GITPOD_REPO_ROOT"
